	pipeline {
		agent any
		environment {
			STACK_NAME_PREFIX = "${env.JOB_NAME}"
			AWS_ACCESS_KEY_ID = credentials('dtcc_aws_access_key_id')
			AWS_SECRET_ACCESS_KEY = credentials('dtcc_aws_secret_access_key')
		}
		parameters {
			string(name: 'awsBin', defaultValue: 'aws')
			string(name: 'awsDefaultRegion', defaultValue: 'us-east-1')
			string(name: 'applicationID', description: 'Application ID (three letters)', defaultValue: 'dap')
			string(name: 'environment', description: 'Environment', defaultValue: 'qa-perf')
			

			// Template-specific parameters
		}
		stages {
			stage('Checkout and Setup CLI') {
				steps {
					checkout scm
					sh params.awsBin + ' configure set aws_access_key_id $AWS_ACCESS_KEY_ID'
					sh params.awsBin + ' configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY'
					sh params.awsBin + ' configure set region ' + params.awsDefaultRegion
					sh params.awsBin + ' configure set output json'
				}
			}
			stage('Check for Existing') {
				steps {
				sh params.awsBin + ' cloudformation list-stacks|grep -P -C 3 "arn.*' + env.awsBin + '.*' + env.awsDefaultRegion + '.*$STACK_NAME_PREFIX-vpc-subnets.*"|grep CREATE_COMPLETE|wc -l > vpcresult'
				sh params.awsBin + ' cloudformation list-stacks|grep -P -C 3 "arn.*' + env.awsBin + '.*' + env.awsDefaultRegion + '.*$STACK_NAME_PREFIX-sg.*"|grep CREATE_COMPLETE|wc -l > sgresult'
				}
			}
			stage('Configure VPC') {
			   	environment {
					numVpcBuilt = sh(script: "cat vpcresult", returnStdout: true).trim()
				}
				steps {
				echo 'Number of VPC'
                echo env.numVpcBuilt
				script {
				if (env.numVpcBuilt == '0') {
					echo 'No VPC exist - Build'
					sh params.awsBin + ' cloudformation create-stack --stack-name $STACK_NAME_PREFIX-vpc-subnets --template-body file:///$WORKSPACE/edap-cloudformation/VPC/vpc-subnets.json'
					sleep 90
					} else {
						echo 'VPC Exist'
						sh params.awsBin + ' cloudformation list-stacks |grep -C 2 $STACK_NAME_PREFIX-vpc-subnets|grep -C 3 CREATE_COMPLETE'
					}
				}
				}
			}
			stage('Configure Security Groups') {
			   	environment {
					numSgBuilt = sh(script: "cat sgresult", returnStdout: true).trim()
				}
				steps {
				echo 'Number of Secruity Groups'
                echo env.numSgBuilt
				script {
				if (env.numSgBuilt == '0') {
					echo 'No Security Groups exist - Build'
					sh params.awsBin + ' cloudformation create-stack --stack-name $STACK_NAME_PREFIX-sg --template-body file:///$WORKSPACE/edap-cloudformation/VPC/security-groups.json'
					} else {
						echo 'Security Groups Exist'
						sh params.awsBin + ' cloudformation list-stacks |grep -C 2 $STACK_NAME_PREFIX-sg|grep -C 3 CREATE_COMPLETE'
					}
				}
				}
			}
	}
	}